#!/bin/bash

# add kubernetes apt repository
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

# install kubernetes from apt sources
apt-get install -y --allow-change-held-packages kubeadm kubelet kubectl
apt-mark hold kubeadm kubelet kubectl
