#!/bin/bash

# install tools
apt-get install -y curl

# add docker apt repository
sudo scripts/install-docker

# add kubernetes apt repository
sudo scripts/install-kubernetes

# initialize kubernetes master
sudo scripts/start-kubernetes
