#!/bin/bash

# install tools
apt-get install -y curl

# add docker apt repository
apt-get update
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# install docker from apt sources
apt-get install -y docker-ce docker-ce-cli containerd.io

# add kubernetes apt repository
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

# install kubernetes from apt sources
apt-get install -y --allow-change-held-packages kubeadm kubelet kubectl
apt-mark hold kubeadm kubelet kubectl

# initialize kubernetes master
kubeadm init --apiserver-advertise-address 192.168.56.116
