#!/bin/bash

# add docker apt repository
apt-get update
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# install docker from apt sources
apt-get install -y docker-ce docker-ce-cli containerd.io
